### ISSUE TITLE
[FEATURE] Backport variables

### ISSUE THREAD

**Issue by cad3264** [NGSpace/hudder#13]
**Is your feature request related to a problem? Please describe.**
I was working on my hud, looking at the docs, and i was trying to do %iscreative ...%, but it wasnt working, i tried {iscreative} and it outputted iscreative, then i realized that it was because i was on 1.20.1 when iscreative was added on 1.20.5.

**Describe the solution you'd like**
Adding support for newer variables to older versions

**Comment by NGSpace** [comment]
I'll try to backport all variables but some may not work as the require a lot of work to get working.

**Comment by NGSpace** [comment]
Done https://modrinth.com/mod/hudder/version/R9gBMSKO

**Comment by cad3264** [comment]
Alright, thanks!
