### ISSUE TITLE
Item/armor durability variable?

### ISSUE THREAD

**Issue by pavlik609** [NGSpace/hudder#2]
Is there a variable for the durabilities of your gear?
If not can you please add it? Would be really helpfull!

**Comment by NGSpace** [comment]
Sorry for the late response, I was sleeping!

I will add held item durability in the next update!

**Comment by NGSpace** [comment]
And armor durability too!

**Comment by pavlik609** [comment]
Ah no worries, thanks in advance!

**Comment by NGSpace** [comment]
{held_item_durability}
{helmet_durability}
{chestplate_durability}
{leggings_durability}
{boots_durability}
{offhand_durability}

Have all been added to v3!

as well as:
```js
;durability, slot_number, variable_name;
```
and
```js
getItem(Number slot).durability
```
on javascript
