### ISSUE TITLE
Variable, "{worldtime}"/"{world_time}" does nothing..

### ISSUE THREAD

**Issue by electra-04** [NGSpace/hudder#9]
I tried to use the worldtime variable in my HUD, hudder decided to display the text, 'worldtime', instead of actually printing out the ingame worldtime.

Here is the contents of my HUD file with some other variables that I added just to test:

%fps<30, "&fFPS: &c{fps}", fps<60, "&fFPS: &e{fps}", "&fFPS: &a{fps}"%
{health}
{hp}
{worldtime}
{blocklight}
{operating_system}

I am on Linux Pop_Os! with Fabric 0.15.11

**Comment by NGSpace** [comment]
What Hudder and Minecraft version are you using?

**Comment by electra-04** [comment]
Minecraft Java 1.20.1 and Hudder 3.0.0 from Modrinth

**Comment by NGSpace** [comment]
The "world_time" variable was only added at Hudder 3.2.0.

Fortunately I was able to backport it to 3.0.0 for 1.20.1 and uploaded the jar to this project's [github releases page](https://github.com/NGSpace/hudder/releases)

**Comment by NGSpace** [comment]
Changes to the code were also pushed directly to the "1.20.1" branch.

**Comment by electra-04** [comment]
Ok, thank you for your help!

**Comment by electra-04** [comment]
Ok, thank you for your help!
